# This file was generated by GoReleaser. DO NOT EDIT.
cask "mkit" do
  version "0.21.1"

  on_macos do
    on_arm do
      sha256 "22f8825d141b3bc9367e39ec319b13eb39564070ebfed999f8dfb016bd2e7018"
      url "https://github.com/masterik/mk-toolkit/releases/download/v#{version}/mkit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "97e287073cc22e30aaad951dffb2b4d3896a0f0f9fe26b90cebd939bb5aa528c"
      url "https://github.com/masterik/mk-toolkit/releases/download/v#{version}/mkit_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "mkit"
  desc "Coding-workflow skills for Claude Code — Go CLI plus a shared Claude Code plugin."
  homepage "https://github.com/masterik/mk-toolkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mkit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/mkit"]
    end
  end

  # No zap stanza required
end
