# This file was generated by GoReleaser. DO NOT EDIT.
cask "mkit" do
  version "0.19.0"

  on_macos do
    on_arm do
      sha256 "b83f20e072081efbd710d05b2b0108ded7d40d485b1e97dbe0dceeaecd708282"
      url "https://github.com/masterik/mk-toolkit/releases/download/v#{version}/mkit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "026a304c073129d0c048f62ae73556889cacb885b6a0d787afda379c604a00cf"
      url "https://github.com/masterik/mk-toolkit/releases/download/v#{version}/mkit_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "mkit"
  desc "Coding-workflow skills for Claude Code — Go CLI plus a shared Claude Code plugin."
  homepage "https://github.com/masterik/mk-toolkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mkit"

  # No zap stanza required
end
