# This file was generated by GoReleaser. DO NOT EDIT.
cask "mkit" do
  version "0.21.0"

  on_macos do
    on_arm do
      sha256 "3beba28da86a10f14db7a80623cb8b08dba2414d6b1ff7fa7af7d67651dcb0c6"
      url "https://github.com/masterik/mk-toolkit/releases/download/v#{version}/mkit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6ba0da7a736d63177d6a53fc79189d644372dd971ac6c294b80857e6b439d33a"
      url "https://github.com/masterik/mk-toolkit/releases/download/v#{version}/mkit_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "mkit"
  desc "Coding-workflow skills for Claude Code — Go CLI plus a shared Claude Code plugin."
  homepage "https://github.com/masterik/mk-toolkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mkit"

  # No zap stanza required
end
